allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  netlify-cli: true
  sharp: true
  svelte-preprocess: true
  unix-dgram: true
minimumReleaseAgeExclude:
  - crossws@0.4.15
  - electron-to-chromium@1.5.449
  - svelte@5.57.2
overrides:
  '@fastify/static@<=10.1.1': ^10.1.2
  cookie@<0.7.0: ^0.7.0
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
  postcss-selector-parser@<7.1.6: ^7.1.6
  sharp@<0.35.5: ^0.35.5
  toml@<4.2.0: ^4.2.0
